//
//  DisplayFlashCardWorker.swift
//  CleanQuiz
//
//  Created by Rod Schmidt on 1/1/17.
//  Copyright (c) 2017 infiniteNIL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class DisplayFlashCardWorker
{
    private let store: FlashCardsStore

    // MARK: - Business Logic

    init(cardsStore: FlashCardsStore)
    {
        self.store = cardsStore
    }

    func fetchFlashCards(completionHandler: @escaping (FlashCardsStoreResult) -> Void)
    {
        store.fetchFlashCards { (result: FlashCardsStoreResult) in
            completionHandler(result)
        }
    }
}

