//
//  DisplayFlashCardPresenter.swift
//  CleanQuiz
//
//  Created by Rod Schmidt on 1/1/17.
//  Copyright (c) 2017 infiniteNIL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DisplayFlashCardPresenterInput
{
    func presentFlashCard(response: DisplayFlashCard.Response.FetchFlashCard)
    func presentError(_ error: FlashCardsStoreError)
}

protocol DisplayFlashCardPresenterOutput: class
{
    func displayFlashCard(viewModel: DisplayFlashCard.ViewModel)
}

class DisplayFlashCardPresenter: DisplayFlashCardPresenterInput
{
    weak var output: DisplayFlashCardPresenterOutput!

    // MARK: - Presentation logic

    func presentFlashCard(response: DisplayFlashCard.Response.FetchFlashCard)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = DisplayFlashCard.ViewModel(questionText: response.card.question,
                                                   answerText: response.card.answer,
                                                   nextQuestionEnabled: !response.isLastCard,
                                                   revealAnswerEnabled: response.isAnswerHidden)
        output.displayFlashCard(viewModel: viewModel)
    }

    func presentError(_ error: FlashCardsStoreError)
    {
    }
}
