//
//  DisplayFlashCardModels.swift
//  CleanQuiz
//
//  Created by Rod Schmidt on 1/1/17.
//  Copyright (c) 2017 infiniteNIL. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct DisplayFlashCard
{
    struct Request
    {
        struct FetchFlashCard
        {
        }

        struct DisplayNextFlashCard
        {
        }

        struct RevealAnswer
        {

        }
    }

    struct Response
    {
        struct FetchFlashCard
        {
            let card: FlashCard
        }
    }

    struct ViewModel
    {
        let questionText: String
        let answerText: String
    }
}
